# This is an updated config for using I3D on ActivtyNet, resulting in slightly
# better performance. To reproduce the setting in our paper, set
# max_seq_len: 160,
# n_mha_win_size: [11, 11, 11, 11, -1, -1],

dataset_name: anet
train_split: ['training']
val_split: ['validation']
dataset: {
  json_file: ./data/anet_1.3/annotations/anet1.3_i3d_filtered.json,
  feat_folder: ./data/anet_1.3/i3d_features,
  file_prefix: v_,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 2048,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 25,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  # upsample the features to a fixed length of 192
  max_seq_len: 192,
  force_upsampling: True,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  # 192 - 96 - 48 - 24 - 12 - 6
  n_mha_win_size: [7, 7, 7, 7, 7, -1],
  n_head: 4,
  embd_dim: 256,
  fpn_dim: 256,
  head_dim: 256,
  use_abs_pe: True,
}
opt: {
  learning_rate: 1.0e-4,
  epochs: 20,
  weight_decay: 1.0e-4, # 0.05
}
loader: {
  batch_size: 16,
}
train_cfg: {
  init_loss_norm: 200,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
  droppath: 0.1,
  loss_weight: 2.0,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.9,
  pre_nms_topk: 2000,
  # max of 100 predictions per video
  max_seg_num: 100,
  min_score: 0.001,
  # score fusion
  multiclass_nms: False,
  nms_sigma : 0.75,
  ext_score_file: ./data/anet_1.3/annotations/cuhk_val_simp_share.json,
  duration_thresh: 0.001,
}
output_folder: ./ckpt/

# DINO DETR
detr: {
  num_classes: 1,
  num_queries: 100, # 756
  temporal_length: 384,
  lr: 1.0e-4, # 1.0e-3
  lr_linear_proj_mult: 0.1,
  lr_linear_proj_names: [], # ['reference_points', 'sampling_offsets']
  hidden_dim: 256,
  num_feature_levels: 1,
  input_dim: 256,
  aux_loss: True,
  enc_layers: 2,
  dec_layers: 4,
  enc_n_points: 4,
  dec_n_points: 4,
  two_stage: False,
  eos_coef: 0.1,
  set_cost_class: 2, # 6
  set_cost_bbox: 5, # 5
  set_cost_giou: 2, # 2
  weight_loss_ce: 2, # 2
  weight_loss_bbox: 5, # 5
  weight_loss_giou: 2, # 2
  weight_loss_KK: 5,
  weight_loss_QQ: 5,
  use_KK: True,
  use_QQ: True,
  with_act_reg: False,
  weight_loss_act: 4,
  weight_decay: 1.0e-4,
  nheads: 8,
  dropout: 0.1,
  dim_feedforward: 1024,
  pre_norm: False,
  scalar: 5,
  label_noise_scale: 0.2,
  box_noise_scale: 0.4,
  num_patterns: 0,
  temperature: 1.0,
  use_dn: False,
  dn_number: 100,
  dn_box_noise_scale: 0.4,
  dn_label_noise_ratio: 0.5,
  dn_labelbook_size: 2,
  focal_alpha: 0.25,
  use_dab: True,
  position_embedding: "sine",
}