dataset_name: thumos
train_split: ['validation']
val_split: ['test']
dataset: {
  json_file: ./data/thumos/annotations/thumos14.json,
  feat_folder: ./data/thumos/i3d_features,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20, # 20
  downsample_rate: 1, # 1
  input_dim: 2048,
  feat_stride: 4, # 4
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304, # 2304
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19,
}
opt: {
  learning_rate: 0.0001,
  epochs: 30,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
   multiclass_nms: False,
   ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
#  multiclass_nms: True,
}
output_folder: ./ckpt/

# DINO DETR
detr: {
  num_classes: 1,
  num_queries: 20, # 4536
  temporal_length: 2304,
  lr: 1.0e-4,
  lr_linear_proj_mult: 0.1,
  lr_linear_proj_names: ['reference_points', 'sampling_offsets'],
  hidden_dim: 64,
  num_feature_levels: 6,
  input_dim: 512,
  aux_loss: True,
  enc_layers: 2,
  dec_layers: 4,
  enc_n_points: 4,
  dec_n_points: 4,
  two_stage: False,
  eos_coef: 0.1,
  set_cost_class: 2, # 6
  set_cost_bbox: 2, # 5
  set_cost_giou: 5, # 2
  weight_loss_ce: 2, # 2
  weight_loss_bbox: 2, # 5
  weight_loss_giou: 5, # 2
  weight_decay: 1.0e-4,
  nhead: 8,
  dropout: 0.1,
  dim_feedforward: 128,
  pre_norm: False,
  scalar: 5,
  label_noise_scale: 0.2,
  box_noise_scale: 0.4,
  num_patterns: 0,
  temperature: 1.0,
  use_dn: False,
  dn_number: 100,
  dn_box_noise_scale: 0.4,
  dn_label_noise_ratio: 0.5,
  dn_labelbook_size: 2,
  focal_alpha: 0.25
}